name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Or any other version you're using
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}

      - name: Build and Run Selenium Tests
        run: mvn clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports